# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for n8n MCP Server
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies without running prepare or postinstall scripts
COPY package.json package-lock.json tsconfig.json ./
RUN npm install --ignore-scripts

# Copy source and build
COPY src ./src
RUN npm run build

# Production image
FROM node:lts-alpine
WORKDIR /app

# Copy production dependencies
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts

# Copy built files
COPY --from=builder /app/build ./build
COPY README.md LICENSE ./

# Set entrypoint to start the MCP server
ENTRYPOINT ["node", "build/index.js"]
